### ISSUE TITLE
Propagate curl multi call traceback

### ISSUE THREAD

**Issue by pbabinca** [DBuildService/osbs-client#78]
If pycurl (multi) call fails I'm not able to see the reason in the traceback. Could it be more verbose what was actually tried or the original exception?
```
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/koji/daemon.py", line 1161, in runTask
    response = (handler.run(),)
  File "/usr/lib/python2.6/site-packages/koji/tasks.py", line 158, in run
    return koji.util.call_with_argcheck(self.handler, self.params, self.opts)
  File "/usr/lib/python2.6/site-packages/koji/util.py", line 154, in call_with_argcheck
    return func(*args, **kwargs)
  File "/usr/lib/koji-builder-plugins/builder_containerbuild.py", line 101, in handler
    build_json = self.osbs().wait_for_build_to_finish(build.build_id)
  File "/usr/lib/python2.6/site-packages/osbs/api.py", line 80, in wait_for_build_to_finish
    response = self.os.wait_for_build_to_finish(build_id, namespace=namespace)
  File "/usr/lib/python2.6/site-packages/osbs/core.py", line 249, in wait_for_build_to_finish
    build_response = self.wait(build_id, BUILD_FINISHED_STATES, namespace)
  File "/usr/lib/python2.6/site-packages/osbs/core.py", line 219, in wait
    response = self._get(url, stream=True, headers={'Connection': 'close'})
  File "/usr/lib/python2.6/site-packages/osbs/core.py", line 89, in _get
    return self._con.get(url, headers=headers, verify_ssl=self.verify_ssl, **kwargs)
  File "/usr/lib/python2.6/site-packages/osbs/http.py", line 292, in get
    return self.request(url, "get", **kwargs)
  File "/usr/lib/python2.6/site-packages/osbs/http.py", line 256, in request
    raise RuntimeError("error during doing curl_multi")
RuntimeError: error during doing curl_multi
```

**Comment by TomasTomecek** [comment]
We'll release new version of osbs-client today with updated handling of exceptions. That should solve your issue.

**Comment by twaugh** [comment]
FWIW, that code now looks like:
```python
 raise OsbsNetworkException(url, "error during doing curl_multi", ret)
```
so the only extra information you'll get is the URL (and ret is just `pycurl.E_CALL_MULTI_PERFORM`). I don't think pycurl gives any extra information than that for us to pass on.

**Comment by pbabinca** [comment]
Looking at the code around that runtime exception - is that:
https://github.com/DBuildService/osbs/blob/master/osbs/http.py#L332
error handling correct?

On the other place I've seen different error handling which takes this as correct behaviour:
https://github.com/DBuildService/osbs/blob/master/osbs/http.py#L199

Similar code can be found in pycurl test code: https://github.com/pycurl/pycurl/blob/master/tests/multi_test.py#L45

**Comment by TomasTomecek** [comment]
> Looking at the code around that runtime exception - is that:
> https://github.com/DBuildService/osbs/blob/master/osbs/http.py#L332
> error handling correct?

That's first request for the chunked response to get headers and response code. If that fails, it means that the whole request failed. So when we are getting chunks and pycurl raises `E_CALL_MULTI_PERFORM`, it just means that all the chunks were already sent. But feel free to object, I might be wrong.

**Comment by pbabinca** [comment]
I still see the problem in staging environment. I'll try to run it with verbose option and I hope this will provide more info to find the cause of the issue.

**Comment by pbabinca** [comment]
I haven't seen this some time now. I'll close it as I assume it is fixed now.
